export enum RuntimeMessageType {
    READY = "READY",
    PING = "PING",
    PONG = "PONG",
    CHECK_MONACO = "CHECK_MONACO",
    MONACO_STATUS = "MONACO_STATUS",
    DISCOVER_MODELS = "DISCOVER_MODELS",
    MODELS_FOUND = "MODELS_FOUND",
    INJECT_MARKDOWN = "INJECT_MARKDOWN",
    INJECTION_STATUS = "INJECTION_STATUS",
    REQUEST = "REQUEST",
    RESPONSE = "RESPONSE"
}
